### ISSUE TITLE
Content Migration does not work in Neo fields in all site groups

### ISSUE THREAD

**Issue by sword3d** [verbb/hyper#116] opened 2024-03-13 17:31 UTC
### Describe the bug

We have two site groups. Group A has two sites, Group B has 5 sites. Content migration works fine in non-Neo fields. But doesn’t work in Group B in Neo fields. Group A is fine. I’m attaching some screenshot. Happy to provide more debugging information.

### Steps to reproduce

![Screenshot_1](https://github.com/verbb/hyper/assets/4801308/442fedd7-69ec-4ba9-a96b-436cfa7df6a9)
![Screenshot_2](https://github.com/verbb/hyper/assets/4801308/3aa54588-7e21-42b4-9a57-722e915716fe)
![Screenshot_3](https://github.com/verbb/hyper/assets/4801308/df411217-43c0-44c9-8d1f-7b07236f6e4e)

### Craft CMS version

Craft CMS  4.7.4

### Plugin version

1.1.21

### Multi-site?

Yes

### Additional context

We are migrating from "sebastianlenz/linkfield": "2.1.5"

**Comment by engram-design** [comment] 2024-03-13 23:55
So I can confirm things are working correctly for multi-sites, but might be unique to multiple groups.

Can you confirm your Neo field "Propagation Method" and the "Translation Method" of your Typed Link field?

**Comment by sword3d** [comment] 2024-03-14 12:48
Typed Link field -> "Translation Method" -> Translate for each site
Neo field  -> "Propagation Method" -> Save blocks to other sites in the same site group

**Comment by engram-design** [comment] 2024-03-14 14:49
Okay, just testing that and the migration is working as expected on my end, with content being migrated across properly.

Any errors in the migration feedback for either the fields themselves, or the content?

**Comment by sword3d** [comment] 2024-03-18 07:54
No errors.
![Screenshot_5](https://github.com/verbb/hyper/assets/4801308/ae774905-070e-4bde-8132-b86bfc629050)

**Comment by engram-design** [comment] 2024-03-19 13:32
Thanks for confirming, that does indeed seem fine. Any chance of being able to send your database from _before_ your migration to Hyper? If so, send to `support@verbb.io` and we can get to the bottom of it. Otherwise, we'll keep at replicating it.

**Comment by sword3d** [comment] 2024-03-20 08:50
Sent it by mail.

**Comment by engram-design** [comment] 2024-03-20 15:16
Thanks for sending that through, that was a big help. I'm not sure if my link field is out of date, or yours is, but looks like we weren't handling the `siteId` of linked elements correctly for Typed Link migration. This is despite it actually working on my end, but I could replicate it with your setup.

Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.22"`

**Comment by sword3d** [comment] 2024-03-21 08:13
Thank you for the fix.
I can confirm that this works.

**Comment by engram-design** [comment] 2024-03-22 10:54
Fixed in [1.1.23](https://github.com/verbb/hyper/releases/tag/1.1.23)

**Closed as completed by engram-design** 2024-03-22 10:54 UTC
