### ISSUE TITLE
Exception error thrown when migrating from Typed Link

### ISSUE THREAD

**Issue by strandofgenius** [verbb/hyper#102] opened 2023-11-09 17:23 UTC
### Describe the bug

I am getting an exception error when trying to migrate from Type Link. It looks like some fields migrated, but not all of them. This particular one that I'm referencing is nested within a Matrix -> Super Table -> Matrix. It looks like there may have been a similar issue with LinkIt (https://github.com/verbb/hyper/issues/75)?

```
Preparing to migrate field “linkField” (0879b3b9-cc03-4515-a8af-b1eecb53ffbf).
Exception: [] (/craft-site/vendor/verbb/hyper/src/migrations/MigrateTypedLinkField.php:148)
#0 /craft-site/vendor/verbb/hyper/src/migrations/PluginFieldMigration.php(39): verbb\hyper\migrations\MigrateTypedLinkField->processFieldSettings()
#1 /craft-site/vendor/craftcms/cms/src/db/Migration.php(49): verbb\hyper\migrations\PluginFieldMigration->safeUp()
#2 /craft-site/vendor/verbb/hyper/src/console/controllers/MigrateController.php(66): craft\db\Migration->up()
#3 /craft-site/vendor/verbb/hyper/src/console/controllers/MigrateController.php(34): verbb\hyper\console\controllers\MigrateController->_migrate('verbb\\hyper\\mig...')
#4 [internal function]: verbb\hyper\console\controllers\MigrateController->actionTypedLinkField()
#5 /craft-site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /craft-site/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 /craft-site/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('typed-link-fiel...', Array)
#8 /craft-site/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('typed-link-fiel...', Array)
#9 /craft-site/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('hyper/migrate/t...', Array)
#10 /craft-site/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('hyper/migrate/t...', Array)
#11 /craft-site/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('hyper/migrate/t...', Array)
#12 /craft-site/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#13 /craft-site/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#14 /craft-site/craft(13): yii\base\Application->run()
#15 {main}
```

### Steps to reproduce

1. Had a Matrix -> Super Table -> Matrix configuration
2. Installed Hyper
3. Tried to run `./craft hyper/migrate/typed-link-field` command
4. Got the exception error

### Craft CMS version

4.5.10

### Plugin version

1.1.16

### Multi-site?

no

**Comment by engram-design** [comment] 2023-11-10 01:44
Hmm, I can't reproduce this with a few similar field setups (all sorts of combos of Matrix and Super Table). There should be errors logged here at `Exception: []` but they're empty. But the Matrix field in the one with the issue saving (I'm not sure which one of yours it is), but there are no errors to state what the error is.

Any chance you can export the field and send it through, using something like Field Manager to export it? Does saving the Matrix field before migrating to Hyper throw any errors (so just saving the field)?

**Comment by strandofgenius** [comment] 2023-11-10 17:23
There are no errors when saving the original matrix field. The Typed Link field inside the second matrix block nested in the Super Table field appears to be the one that throws the exception.

**Comment by engram-design** [comment] 2023-11-10 22:41
Hmm. Let me know if you can send through the export of your field (welcome to send to `support@verbb.io`) so I can replicate your field.

**Comment by engram-design** [comment] 2023-11-13 23:58
Thanks for sending that through. I can see the error is related to the blocktypes of the field (the errors will be incorporated into the migration helper for the next release, so it's easier to detect). 

It's flagging `“content” is a reserved word.` for a blocktype (`threeColumnWImage`), which isn't flagged when saving the Matrix field, as the Super Table context as the middle field doesn't enforce this. But that migration will try and save the Matrix field within the Super Table field on its own, due to the complex migration that Typed Link requires. 

So this is probably more a Super Table issue than anything else. Super Table should be flagging that `content` is an invalid blocktype handle for the inner Matrix field.

So the resolution here would be to rename your inner Matrix blocktype to a valid handle, then run the Hyper migration.
- `threeColumnWImage` > `rows` > `columnContent` > `content`
- `employees` > `rows` > `columnContent` > `content`

I'll look at making this fix in Super Table, as those fields shouldn't be saving as they are now.

**Comment by strandofgenius** [comment] 2023-11-14 15:56
Were you able to see an error somewhere in the logs? I tried looking through the logs and didn't find anything. 

Thank you for looking into this. It sounds like I will need to rename those fields named `content`, and it should start working as expected.

**Comment by strandofgenius** [comment] 2023-11-14 17:21
I can confirm that after changing the field name and handle the migration was successful.

**Comment by engram-design** [comment] 2023-11-14 20:41
No error in the logs, but I've added extra logging now to output any errors for the field *and* the blocktypes for Matrix/Super Table fields, which is where the error was here.

Will follow up this issue in Super Table's repo.

**Closed as completed by engram-design** 2023-11-14 20:41 UTC
